- hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
    - name: python3 is installed
      raw: pkg install -y python3
      register: install_python
      changed_when: "'INSTALLED' in install_python.stdout"

    - name: host facts are gathered
      setup:

  vars:
    ansible_python_interpreter: /usr/local/bin/python3

  tasks:
    - copy:
        content: |
          sshd_enable="YES"
          ntpd_enable="YES"
        dest: /tmp/foobar.conf

    - blockinfile:
        block: |
          sendmail_enable="NO"
          sendmail_submit_enable="NO"
          sendmail_outbound_enable="NO"
          sendmail_msp_queue_enable="NO"
        path: /tmp/foobar.conf
        marker: "# {mark}"
        marker_begin: "sendmail {{ '{' }}"
        marker_end: "{{ '}' }}"

    - blockinfile:
        block: |
          firewall_enable="YES"
          firewall_logging="YES"
          firewall_script="/etc/ipfw.rules"
          firewall_nat_enable="YES"
          gateway_enable="YES"
        path: /tmp/foobar.conf
        marker: "# {mark}"
        marker_begin: "ipfw {{ '{' }}"
        marker_end: "{{ '}' }}"

    - blockinfile:
        block: |
          firewall_enable="NO"
        path: /tmp/foobar.conf
        marker: "# {mark}"
        marker_begin: "ipfw {{ '{' }}"
        marker_end: "{{ '}' }}"
