version: "3"

services:
  influxdb:
    image: influxdb:1.4
    ports:
      - 8086:8086
    volumes:
      - $PWD/db:/var/lib/influxdb

  gateway:
    image: gateway
    ports:
      - 8080:8080
    environment:
      - GATEWAY_INFLUXDB_ADDRESS=influxdb:8086
