version: "3"

services:
  influxdb:
    image: influxdb:1.4
    ports:
      - 8086:8086
    volumes:
      - $PWD/db:/var/lib/influxdb

  gateway:
    image: gateway
    links:
      - influxdb
    ports:
      - 8080:8080
    environment:
      - GATEWAY_INFLUXDB_URL=http://influxdb:8086
      - GATEWAY_ADDRESS=:8080
