- hosts: default
  become: true
  vars:
    - wan_interface: eth0

  tasks:
    - name: network security parameters are set
      copy: src=60-network_security.conf dest=/etc/sysctl.d/ mode=0600

    - name: firewall service is put into place
      copy: src=firewall.service dest=/etc/systemd/system/ mode=0600

    - name: firewall script is put into place
      template: src=firewall.sh.j2 dest=/etc/firewall.sh mode=0700
      notify:
        - restart firewall
        - check connection

    - name: firewall is enabled
      service: name=firewall enabled=yes

  handlers:
    - name: restart firewall
      shell: "sleep 2 && systemctl restart firewall"
      async: 1
      poll: 0

    - name: check connection
      local_action:
        module: wait_for
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        delay: 2
      become: false
