- hosts: default
  become: true
  vars:
    - wan_interface: eth0

  tasks:
    - name: network security parameters are set
      copy: src=60-network_security.conf dest=/etc/sysctl.d/ mode=0600

    - name: firewall service is put into place
      copy: src=firewall.service dest=/etc/systemd/system/ mode=0600

    - name: firewall script is put into place
      template: src=firewall.sh.j2 dest=/etc/firewall.sh mode=0700

    - name: ensure firewall is running
      service: name=firewall state=started enabled=yes
