- hosts: all

  become: true

  tasks:
    - name: required packages are installed
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
        - python-docker

    - name: apt signing key for docker repository is registered
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: docker repository is registered
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
        state: present

    - name: docker is installed
      apt:
        name: docker-ce
        state: present

    - name: admin may use docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: hello-world container runs
      command: docker run hello-world
