- hosts: all
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    postgres_version: 12
    postgres_cluster: main
    postgres_password: 18c0cc32a41a7843abebca89e21667d7  # example
    walg_version: v0.2.14
    walg_service_account: _service_account.json
    walg_bucket: test-923cc233d715a13f/backup  # example
    walg_retained_backups: 7

  roles:
    - ubuntu-system
    - postgres-server
    - postgres-backup
