- hosts: default
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    # Debain system

    - name: apt cache is up to date
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # MinIO

    - name: minio group is present
      group:
        name: minio
        state: present

    - name: minio user is present
      user:
        name: minio
        group: minio
        state: present

    - name: minio data directory is present
      file:
        path: /var/lib/minio
        state: directory
        owner: minio
        group: minio
        mode: 0750

    - name: minio existence is checked
      stat:
        path: /usr/sbin/minio
      register: _stat_minio

    - name: minio is installed
      get_url:
        url: https://dl.min.io/server/minio/release/linux-amd64/minio
        dest: /usr/sbin/minio
        mode: 0755
      when: not _stat_minio.stat.exists

    - name: minio config is up
      template:
        src: minio.j2
        dest: /etc/default/minio
        owner: minio
        group: minio
        mode: 0640

    - name: minio service unit is up
      copy:
        src: minio.service
        dest: /etc/systemd/system/

    - name: minio service is activated
      service:
        name: minio
        state: started
        enabled: yes
