- hosts: all
  become: yes

  tasks:
    - name: apt cache is up to date
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: packages are installed
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - socat
        - tmux

    - name: listen and send tools are pushed
      copy:
        src: "{{ item }}"
        dest: .
        owner: vagrant
        group: vagrant
        mode: 0755
      with_items:
        - listen-linux
        - send-linux
