- hosts: all
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    postgres_version: 10
    postgres_password: e41fde59a861eb2c878f0313912388b6
    walg_version: v0.2.13
    walg_retained_backups: 5

  tasks:
    - name: ansible prerequisites are installed
      apt:
        name:
          - python3-pexpect
          - python3-psycopg2
        state: present

    # Firewall

    - name: ufw is disabled
      service:
        name: ufw
        state: stopped
        enabled: no

    # PostgreSQL

    - name: postgresql cluster manager is installed
      apt:
        name: postgresql-common
        state: present

    - name: postgresql createcluster config directory is present
      file:
        path: /etc/postgresql-common/createcluster.d
        state: directory

    - name: postgresql default cluster creation is suppressed
      copy:
        content: |
          create_main_cluster = false
        dest: /etc/postgresql-common/createcluster.d/50-suppress_main_cluster.conf

    - name: postgresql is installed
      apt:
        name: "postgresql-{{ postgres_version }}"
        state: present

    - name: postgresql cluster is created
      expect:
        command: >
          pg_createcluster
            --locale C.UTF-8
            --port 5432
            --start
            {{ postgres_version }}
            main
            --
            --pwprompt
        creates: "/var/lib/postgresql/{{ postgres_version }}/main/PG_VERSION"
        responses:
          "(password|again):": "{{ postgres_password }}"

    - name: postgresql auth config is up
      copy:
        src: postgres-hba.conf
        dest: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
        owner: postgres
        group: postgres
        mode: 0640
      notify: restart postgresql

    - name: postgresql overriding config is up
      copy:
        src: postgres-overrides.conf
        dest: "/etc/postgresql/{{ postgres_version }}/main/conf.d/overrides.conf"
        owner: postgres
        group: postgres
        mode: 0640
      notify: restart postgresql

    - name: postgresql is activated
      service:
        name: "postgresql@{{ postgres_version }}-main"
        state: started
        enabled: yes

    - name: postgresql is accessible
      postgresql_ping:
        db: postgres
        login_password: "{{ postgres_password }}"

    # wal-g

    - name: uenv apt repository is added
      apt_repository:
        repo: ppa:snsinfu/uenv
        state: present

    - name: uenv is installed
      apt:
        name: uenv
        state: present

    - name: wal-g directories are present
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /srv/wal-g
        - /srv/wal-g/bin

    - name: wal-g is downloaded
      unarchive:
        src: "https://github.com/wal-g/wal-g/releases/download/{{ walg_version }}/wal-g.linux-amd64.tar.gz"
        dest: /srv/wal-g/bin
        remote_src: yes
        creates: /srv/wal-g/bin/wal-g

    - name: google service account key is up
      copy:
        src: google.json
        dest: /srv/wal-g/google.json
        mode: 0640
        owner: root
        group: postgres

    - name: wal-g gcs environment is up
      template:
        src: gs.env.j2
        dest: /srv/wal-g/gs.env
        mode: 0640
        owner: root
        group: postgres

    # The cron frequency is set to high for testing purpose.

    - name: wal-g backup job script is up
      template:
        src: backup.sh.j2
        dest: /srv/wal-g/backup.sh
        mode: 0755

    - name: wal-g backup job is set up
      cron:
        minute: "*/1"
        job: "/bin/uenv -f /srv/wal-g/gs.env /srv/wal-g/backup.sh"
        user: root
        cron_file: database

  handlers:
    - name: restart postgresql
      service:
        name: "postgresql@{{ postgres_version }}-main"
        state: restarted
