# Server certificate

- name: server cert facts are set
  set_fact:
    _server_privkey: "{{ ca_issue_dir }}/server-private.pem"
    _server_csr: "{{ ca_issue_dir }}/server.csr"
    _server_cert: "{{ ca_issue_dir }}/server.crt"
    _server_dh: "{{ ca_issue_dir }}/server-dh.pem"

- name: private key is created
  openssl_privatekey:
    path: "{{ _server_privkey }}"
    mode: 0600

- name: csr is created
  openssl_csr:
    path: "{{ _server_csr }}"
    privatekey_path: "{{ _server_privkey }}"
    common_name: "{{ vpn_server_name }}"
    key_usage:
      - digitalSignature
    extended_key_usage:
      - serverAuth

- name: certificate is issued
  openssl_certificate:
    path: "{{ _server_cert }}"
    csr_path: "{{ _server_csr }}"
    privatekey_path: "{{ _server_privkey }}"
    provider: ownca
    ownca_path: "{{ ca_cert }}"
    ownca_privatekey_path: "{{ ca_privkey }}"
    ownca_privatekey_passphrase: "{{ ca_pass }}"
    select_crypto_backend: pyopenssl  # Ansible issue #55495

- name: certificate is valid
  command: "openssl verify -CAfile {{ ca_cert }} {{ _server_cert }}"
  changed_when: none

- name: dh is generated (this may take time)
  openssl_dhparam:
    size: 2048
    path: "{{ _server_dh }}"
    mode: 0600
