- hosts: all
  become: yes

  tasks:
    - name: dev tools are installed
      apt:
        name:
          - git
          - golang
        state: present

    - name: rtun project is fetched
      command: go get -d github.com/snsinfu/reverse-tunnel/...

    - name: rtun is built
      command: go build -o /usr/local/bin/rtun github.com/snsinfu/reverse-tunnel/agent/cmd

    - name: rtun service file is installed
      copy:
        src: rtun.service
        dest: /etc/systemd/system

    - name: rtun config file is installed
      copy:
        src: rtun.yml
        dest: /usr/local/etc

    - name: rtun service is activated
      service:
        name: rtun
        state: started
        enabled: yes
