- name: apt cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: max number of file descriptors is increased
  sysctl:
    name: fs.file-max
    value: "65536"
    reload: yes
