- hosts: all
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    postgres_version: 12
    postgres_cluster: main

  roles:
    - debian-system
    - postgres-server
    - postgres-pool
    - postgres-databases
