- hosts: all
  become: yes
  gather_facts: no

  vars:
    ansible_python_interpreter: /usr/local/bin/python3

  pre_tasks:
    - name: python is installed
      raw: pkg install -y python3
      register: install_python
      changed_when: "'INSTALLED' in install_python.stdout"

    - name: ansible is set up
      setup:

  tasks:
    - name: tmux is installed
      pkgng:
        name: tmux
        state: present

    - name: socat is installed
      pkgng:
        name: socat
        state: present

    - name: listen and send tools are pushed
      copy:
        src: "{{ item }}"
        dest: .
        owner: vagrant
        group: vagrant
        mode: 0755
      with_items:
        - listen-freebsd
        - send-freebsd
