- hosts: all
  become: yes

  tasks:
      # https://docs.docker.com/install/linux/docker-ce/ubuntu/
    - name: apt https repository requirements are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
        state: present

    - name: apt signing key for docker repository is registered
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: docker repository is registered
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: docker is installed
      apt:
        name: docker-ce
        state: present

    - name: docker is activated
      service:
        name: docker
        state: started
        enabled: yes

    - name: caprover service unit is up
      copy:
        src: caprover.service
        dest: /etc/systemd/system/

    - name: caprover is activated
      service:
        name: caprover
        state: started
        enabled: yes
