version: "3.7"

services:
  redis:
    image: redis:alpine

  producer:
    image: alpine
    command: /srv/producer-linux
    links:
      - redis
    volumes:
      - ".:/srv"
    environment:
      - REDIS_URL=redis://redis:6379

  consumer:
    image: alpine
    command: /srv/consumer-linux
    links:
      - redis
    volumes:
      - ".:/srv"
    environment:
      - REDIS_URL=redis://redis:6379
