---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint

platforms:
  - name: instance
    box: bento/freebsd-12

provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint

verifier:
  name: testinfra
  lint:
    name: flake8
