---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Sendmail is completely disabled
      rc_conf:
        fragment: |
          sendmail_enable="NO"
          sendmail_submit_enable="NO"
          sendmail_outbound_enable="NO"
          sendmail_msp_queue_enable="NO"

  post_tasks:
    - name: Check rc.conf sendmail line
      lineinfile:
        name: /etc/rc.conf
        line: sendmail_enable="NO"
        state: present
      check_mode: yes
      register: line
      failed_when: (line is changed) or (line is failed)
