- hosts: all
  become: yes
  tasks:
    - name: hosts are configured
      lineinfile:
        path: /etc/hosts
        line: "{{ static_ips[item] }} {{ item }}"
      with_inventory_hostnames:
        - all


- hosts: master
  become: yes
  tasks:
    - name: hoge user is added
      user:
        name: hoge
        password: "{{ 'hoge' | password_hash('sha256') }}"
        state: present
        group: users

    - name: ypserv is installed
      yum:
        name: ypserv
        state: present

    - name: yp domain name is set
      command: "ypdomainname {{ nis_domain }}"

    - name: yp domain name is configured
      lineinfile:
        path: /etc/sysconfig/network
        line: "NISDOMAIN={{ nis_domain }}"
        create: yes

    - name: ypserv securenets are configured
      copy:
        content: |
          host          127.0.0.1
          255.255.255.0 {{ static_ips['master'] | regex_replace('\.\d*$', '.0') }}
        dest: /var/yp/securenets

    - name: ypserv database is updated
      make:
        chdir: /var/yp

    - name: ypserv service is activated
      service:
        name: ypserv
        state: started
        enabled: yes


- hosts: worker
  become: yes
  tasks:
    - name: ypbind is installed
      yum:
        name: ypbind
        state: present

    - name: yp is configured
      template:
        src: yp.conf.j2
        dest: /etc/yp.conf

    - name: nsswitch is configured
      copy:
        src: nsswitch.conf
        dest: /etc/

    - name: ypbind service is activated
      service:
        name: ypbind
        state: started
        enabled: yes

    - name: hoge user is available
      command: id hoge
      changed_when: none
