- name: firewall script is up
  template:
    src: "{{ inventory_hostname }}/ipfw.rules.j2"
    dest: /etc/ipfw.rules
    mode: 0600
  notify: restart ipfw

- name: ipfw_rc.conf is up
  template:
    src: ipfw_rc.conf.j2
    dest: /etc/rc.conf.locals/ipfw_rc.conf
