- name: wal-g directory is present
  file:
    path: /srv/wal-g
    state: directory

- name: wal-g google storage configuration is up
  template:
    src: gs.env.j2
    dest: /srv/wal-g/gs.env
    mode: 0640
    owner: root
    group: postgres

- name: google storage service account key is up
  copy:
    src: "{{ walg_service_account }}"
    dest: /srv/wal-g/gs-service_account.json
    mode: 0640
    owner: root
    group: postgres
