- hosts: all
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ca_dir: /srv/pki
    ca_name: example
    ca_pass: example-oErqzqT3YTvCStrB8bIvcqZRlPgr
    server_name: foo

  tasks:
    - name: ansible module requirements are installed
      apt:
        name: python3-cryptography
        state: present

    # CA

    - name: ca facts are set
      set_fact:
        ca_privkey: "{{ ca_dir }}/ca-private.pem"
        ca_csr: "{{ ca_dir }}/ca.csr"
        ca_cert: "{{ ca_dir }}/ca.crt"
        ca_issue_dir: "{{ ca_dir }}/issue"

    - name: ca directory is present
      file:
        path: "{{ ca_dir }}"
        state: directory
        mode: 0700

    - name: ca-issue directory is present
      file:
        path: "{{ ca_issue_dir }}"
        state: directory
        mode: 0700

    - name: ca private key is created
      openssl_privatekey:
        path: "{{ ca_privkey }}"
        mode: 0600
        cipher: auto
        passphrase: "{{ ca_pass }}"

    - name: ca csr is created
      openssl_csr:
        path: "{{ ca_csr }}"
        privatekey_path: "{{ ca_privkey }}"
        privatekey_passphrase: "{{ ca_pass }}"
        common_name: "{{ ca_name }}"
        key_usage:
          - keyCertSign
          - cRLSign
        basic_constraints:
          - "CA:TRUE"

    - name: ca certificate is issued
      openssl_certificate:
        path: "{{ ca_cert }}"
        csr_path: "{{ ca_csr }}"
        privatekey_path: "{{ ca_privkey }}"
        privatekey_passphrase: "{{ ca_pass }}"
        provider: selfsigned
        select_crypto_backend: pyopenssl  # Ansible issue #55495

    # CRL maintenance is not supported yet
    # https://github.com/ansible/ansible/issues/53789

    # CA-signed server cert

    - name: server cert facts are set
      set_fact:
        _server_privkey: "{{ ca_issue_dir }}/server-private.pem"
        _server_csr: "{{ ca_issue_dir }}/server.csr"
        _server_cert: "{{ ca_issue_dir }}/server.crt"
        _server_dh: "{{ ca_issue_dir }}/server-dh.pem"

    - name: server private key is created
      openssl_privatekey:
        path: "{{ _server_privkey }}"
        mode: 0600

    - name: server csr is created
      openssl_csr:
        path: "{{ _server_csr }}"
        privatekey_path: "{{ _server_privkey }}"
        common_name: "{{ server_name }}"
        key_usage:
          - digitalSignature
        extended_key_usage:
          - serverAuth

    - name: server certificate is issued
      openssl_certificate:
        path: "{{ _server_cert }}"
        csr_path: "{{ _server_csr }}"
        privatekey_path: "{{ _server_privkey }}"
        provider: ownca
        ownca_path: "{{ ca_cert }}"
        ownca_privatekey_path: "{{ ca_privkey }}"
        ownca_privatekey_passphrase: "{{ ca_pass }}"
        select_crypto_backend: pyopenssl  # Ansible issue #55495

    - name: server dh is generated (this may take time)
      openssl_dhparam:
        size: 2048
        path: "{{ _server_dh }}"
        mode: 0600

    # Test

    - name: server cert is valid
      command: "openssl verify -CAfile {{ ca_cert }} {{ _server_cert }}"
      changed_when: none
