- hosts: all
  become: yes

  vars:
    k3s_version: v0.9.1

  tasks:
    - name: k3s is installed
      shell: curl -fsSL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s
      environment:
        INSTALL_K3S_VERSION: "{{ k3s_version }}"
        INSTALL_K3S_EXEC: "server --tls-san {{ k3s_address }} --no-deploy traefik"

    - name: k3s remote config is generated
      shell: |
        sed                                \
          's/127.0.0.1/{{ k3s_address }}/' \
          /etc/rancher/k3s/k3s.yaml        \
        > k3s-remote.yaml

    - name: k3s remote config is downloaded
      fetch:
        src: k3s-remote.yaml
        dest: _k3s.yaml
        flat: yes

    - name: k3s service port is registered
      lineinfile:
        path: /etc/services
        line: "kubernetes 6443/tcp"
        regexp: "^kubernetes "
        state: present

    - name: ufw is disabled
      service:
        name: ufw
        state: stopped
        enabled: no

    - name: netfilter service is installed
      apt:
        name:
          - netfilter-persistent
          - iptables-persistent
        state: present

    - name: iptables rules file is up
      template:
        src: iptables.v4rules.j2
        dest: /etc/iptables/rules.v4
      notify: restart netfilter

    - name: netfilter service is activated
      service:
        name: netfilter-persistent
        state: started
        enabled: yes

  handlers:
    - name: restart netfilter
      service:
        name: netfilter-persistent
        state: restarted
