---
kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:11
          name: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
          ports:
            - containerPort: 5432
              name: postgres

---
kind: Service
apiVersion: v1

metadata:
  name: postgres
  labels:
    app: postgres

spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres
