- name: main user is present
  user:
    name: "{{ main_user }}"
    groups: users,docker

- name: main user is a sudoer
  template:
    src: main_user.j2
    dest: /etc/sudoers.d/main_user
    mode: 0440

- name: injected key is fetched back
  fetch:
    src: /root/.ssh/authorized_keys
    dest: injected_key.pub
    flat: yes

- name: main user uses the injected key
  authorized_key:
    user: "{{ main_user }}"
    key: "{{ lookup('file', 'injected_key.pub') }}"

- name: sshd is properly configured
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
