- name: facts are collected
  set_fact:
    clients_dir: /srv/vpn/clients

- name: clients directory is present
  file:
    path: "{{ clients_dir }}"
    state: directory
    mode: 0700

# Backdoor client

- name: backdoor client config is generated
  include_role:
    name: vpn_clients.create
  vars:
    client_name: backdoor_client
    static_ip: "{{ backdoor_vpn_addr }}"

- name: backdoor client config is pulled back
  fetch:
    src: "{{ clients_dir}}/backdoor_client.ovpn"
    dest: output/
    flat: yes

# Remote clients

- name: remote client configs are generated
  include_role:
    name: vpn_clients.create
  vars:
    client_name: remote_client-{{ item }}
    extra_routes:
      - >
        {{ backdoor_subnet | ipaddr(0) }}
        {{ backdoor_subnet | ipaddr('netmask') }}
        {{ backdoor_vpn_addr }}
  with_items: "{{ vpn_remote_clients }}"

- name: remote client configs are pulled back
  fetch:
    src: "{{ clients_dir }}/remote_client-{{ item }}.ovpn"
    dest: output/
    flat: yes
  with_items: "{{ vpn_remote_clients }}"
