- hosts: all
  become: yes

  tasks:
    - name: ansible prerequisites are installed
      pkgng:
        name:
          - py36-pexpect
        state: present

    - name: openvpn is installed
      pkgng:
        name:
          - easy-rsa
          - openvpn
        state: present

    - name: srv directory is present
      file:
        path: /srv
        state: directory

    - name: rc.conf.local is up
      template:
        src: rc.conf.local.j2
        dest: /etc/rc.conf.local

    # -- Firewall ----------------------------
    - name: ipfw.rules is up
      template:
        src: ipfw.rules.j2
        dest: /etc/ipfw.rules

    # -- CA ----------------------------------
    - name: certs directory is present
      file:
        path: /srv/certs
        state: directory
        mode: 0700

    - name: ca pki is initialized
      command: easyrsa init-pki
      args:
        chdir: /srv/certs
        creates: /srv/certs/pki

    - name: ca is built
      expect:
        command: easyrsa build-ca
        responses:
          "(Re-)?Enter New CA Key Passphrase": "{{ ca_password }}"
          "Common Name": "{{ ca_name }}"
        chdir: /srv/certs
        creates: /srv/certs/pki/ca.crt

    - name: crl is generated
      expect:
        command: easyrsa gen-crl
        responses:
          "Enter pass phrase": "{{ ca_password }}"
        chdir: /srv/certs
        creates: /srv/certs/pki/crl.pem

    # -- Server cert and key -----------------
    - name: server key and cert are built
      expect:
        command: easyrsa build-server-full server nopass
        responses:
          "Enter pass phrase": "{{ ca_password }}"
        chdir: /srv/certs
        creates: /srv/certs/pki/issued/server.crt

    - name: server DH params are generated
      command: easyrsa gen-dh
      args:
        chdir: /srv/certs
        creates: /srv/certs/pki/dh.pem

    # -- OpenVPN deployment ------------------
    - name: vpn directory is present
      file:
        path: /srv/vpn
        state: directory
        mode: 0700

    - name: certs and keys are deployed to vpn config directory
      file:
        src: "{{ item }}"
        dest: "/srv/vpn/{{ item | basename }}"
        state: link
      with_items:
        - /srv/certs/pki/ca.crt
        - /srv/certs/pki/crl.pem
        - /srv/certs/pki/issued/server.crt
        - /srv/certs/pki/private/server.key
        - /srv/certs/pki/dh.pem

    - name: tls-auth key is generated
      command: openvpn --genkey --secret /srv/vpn/tls_auth.key
      args:
        creates: /srv/vpn/tls_auth.key

    - name: openvpn config is up
      template:
        src: openvpn.conf.j2
        dest: /srv/vpn/openvpn.conf
      notify:
        - restart openvpn

  handlers:
    - name: restart openvpn
      service:
        name: openvpn
        state: restarted
