- hosts: all
  become: yes
  tasks:
    - name: ssl directories are present
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /etc/ssl/csr
        - /etc/ssl/certs
        - /etc/ssl/private
        - /etc/nginx/ssl

    - name: CA cert private key is generated
      command: openssl genrsa -out private/ca.key 4096
      args:
        chdir: /etc/ssl
        creates: private/ca.key

    - name: CA csr is generated
      command: openssl req -new -key private/ca.key -subj "/O=MyCA" -out csr/ca.csr
      args:
        chdir: /etc/ssl
        creates: csr/ca.csr

    - name: CA cert is generated
      command: openssl x509 -sha256 -days 365 -req -in csr/ca.csr -signkey private/ca.key -out certs/ca.cert
      args:
        chdir: /etc/ssl
        creates: certs/ca.cert

    - name: server private key is generated
      command: openssl genrsa -out server.key 4096
      args:
        chdir: /etc/nginx/ssl
        creates: server.key

    - name: server csr is generated
      command: openssl req -new -key server.key -subj "/CN=localhost" -out server.csr
      args:
        chdir: /etc/nginx/ssl
        creates: csr/server.csr

    - name: server cert is generated
      command: openssl x509 -sha256 -days 365 -req -in server.csr -CA /etc/ssl/certs/ca.cert -CAkey /etc/ssl/private/ca.key -set_serial 1 -out server.cert
      args:
        chdir: /etc/nginx/ssl
        creates: server.cert

    - name: server cert is valid
      command: openssl verify -CAfile /etc/ssl/certs/ca.cert /etc/nginx/ssl/server.cert
      changed_when: none

    - name: nginx is installed
      apt:
        name: nginx
        state: present

    - name: nginx is configured
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx

    - meta: flush_handlers

    - name: nginx is started
      service:
        name: nginx
        state: started

    - name: local https connection is working
      command: curl --silent --show-error --output /dev/null https://localhost/
      args:
        warn: no
      changed_when: none

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
