version: "3.7"

services:
  redis:
    image: redis:alpine

  web:
    image: alpine
    command: /srv/main-linux
    links:
      - redis
    volumes:
      - ".:/srv"
    environment:
      - REDIS_URL=redis://redis:6379
