version: "3.7"

services:
  redis:
    image: redis:alpine

  web:
    image: alpine
    command: /srv/web
    links:
      - redis
    volumes:
      - ".:/srv"
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - REDIS_URL=redis://redis:6379
